import { useState } from 'react';
import { Check, Copy, FileText, Hash, Lightbulb, Loader2, RefreshCw, Save, Sparkles, Target, Type } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { LANGUAGES } from '@/types/navigation';
import SectionHeader from '@/components/SectionHeader';

const tools = [
  { id: 'ideas', label: 'YouTube ideas', icon: Lightbulb }, { id: 'titles', label: 'Video titles', icon: Type }, { id: 'descriptions', label: 'Descriptions', icon: FileText }, { id: 'scripts', label: 'Scripts', icon: FileText }, { id: 'captions', label: 'Captions', icon: Target }, { id: 'hashtags', label: 'Hashtags', icon: Hash }, { id: 'shorts', label: 'Shorts ideas', icon: Sparkles }, { id: 'improve', label: 'Improve script', icon: RefreshCw }, { id: 'thumbnail', label: 'Thumbnail concepts', icon: Target },
];

type Result = { title: string; body: string };
export default function AiToolsView() {
  const [tool, setTool] = useState(tools[0].id); const [topic, setTopic] = useState(''); const [language, setLanguage] = useState('English'); const [loading, setLoading] = useState(false); const [results, setResults] = useState<Result[]>([]); const [copied, setCopied] = useState<number | null>(null); const activeTool = tools.find((item) => item.id === tool) ?? tools[0];
  function generate() { if (!topic.trim()) return; setLoading(true); setTimeout(() => { const labels = activeTool.label; const generated = Array.from({ length: 3 }, (_, index) => ({ title: `${labels.replace(/^./, (char) => char.toUpperCase())} ${index + 1}`, body: `A fresh ${language.toLowerCase()}-language concept for “${topic.trim()}”. Hook your audience in the first five seconds, build a clear story arc, and close with a memorable call to action.` })); setResults(generated); setLoading(false); void supabase.from('ai_results').insert({ tool_type: tool, topic: topic.trim(), language, content: generated.map((item) => `${item.title}: ${item.body}`) }); }, 900); }
  async function copy(text: string, index: number) { await navigator.clipboard?.writeText(text); setCopied(index); setTimeout(() => setCopied(null), 1500); }
  return <div className="space-y-7 animate-fade-in-up"><SectionHeader eyebrow="Creative intelligence" title="AI creator tools" description="Turn a rough thought into a ready-to-publish content plan." />
    <div className="grid lg:grid-cols-[280px_1fr] gap-5"><div className="glass-card p-3 h-fit"><p className="px-3 py-2 text-[10px] uppercase tracking-widest text-gray-600">Choose a tool</p><div className="grid grid-cols-2 lg:grid-cols-1 gap-1">{tools.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => setTool(item.id)} className={`flex items-center gap-2 px-3 py-2.5 rounded-lg text-xs text-left transition-colors ${tool === item.id ? 'bg-cyan-400/10 text-cyan-300 border border-cyan-400/20' : 'text-gray-500 hover:bg-white/5 hover:text-white border border-transparent'}`}><Icon className="w-4 h-4" />{item.label}</button>; })}</div></div>
      <div className="space-y-5"><div className="glass-card p-5 sm:p-6"><div className="flex items-center gap-3 mb-5"><div className="w-10 h-10 rounded-xl bg-cyan-400/10 flex items-center justify-center"><Sparkles className="w-5 h-5 text-cyan-300" /></div><div><h3 className="font-semibold">Generate {activeTool.label}</h3><p className="text-xs text-gray-600">Describe what you want to create</p></div></div><textarea value={topic} onChange={(event) => setTopic(event.target.value)} placeholder="Tell me about your channel, audience, or next big idea..." className="input-field w-full min-h-28 p-4 text-sm resize-none" /><div className="flex flex-col sm:flex-row gap-3 mt-4"><select value={language} onChange={(event) => setLanguage(event.target.value)} className="input-field px-4 py-3 text-sm flex-1">{LANGUAGES.map((item) => <option key={item}>{item}</option>)}</select><button disabled={loading || !topic.trim()} onClick={generate} className="neon-button-primary px-5 py-3 rounded-xl text-sm inline-flex items-center justify-center gap-2 disabled:opacity-50">{loading ? <><Loader2 className="w-4 h-4 animate-spin" /> Creating...</> : <><Sparkles className="w-4 h-4" /> Generate</>}</button></div></div>
        {results.length > 0 && <div className="space-y-3 animate-fade-in"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">Your results</h3><button onClick={generate} className="text-xs text-cyan-400 inline-flex items-center gap-1"><RefreshCw className="w-3 h-3" /> Regenerate</button></div>{results.map((result, index) => <div key={result.title} className="glass-card p-4"><div className="flex items-start gap-3"><div className="w-7 h-7 rounded-lg bg-purple-400/10 flex items-center justify-center text-xs text-purple-300">{index + 1}</div><div className="flex-1"><h4 className="text-sm font-medium">{result.title}</h4><p className="text-xs text-gray-400 leading-relaxed mt-2">{result.body}</p><div className="flex items-center gap-3 mt-4"><button onClick={() => void copy(result.body, index)} className="text-[11px] text-gray-500 hover:text-white inline-flex items-center gap-1">{copied === index ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}{copied === index ? 'Copied' : 'Copy'}</button><button onClick={() => void supabase.from('ai_results').insert({ tool_type: tool, topic, language, content: [result.body] })} className="text-[11px] text-gray-500 hover:text-cyan-300 inline-flex items-center gap-1"><Save className="w-3 h-3" /> Save</button></div></div></div></div>)}</div>}
      </div></div></div>;
}
